name: captain-olimar

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/workspace/backend:cached
      - ./frontend:/workspace/frontend:cached
      - ./.devcontainer:/workspace/.devcontainer:cached
      - ./compose.yaml:/workspace/compose.yaml:cached
      - ./.env:/workspace/.env:cached
      - backend-node-modules:/workspace/backend/node_modules
    working_dir: /workspace/backend
    command: yarn run start:dev
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    env_file:
      - .env
    environment:
      - PORT=3001
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/workspace/frontend:cached
      - frontend-node-modules:/workspace/frontend/node_modules
    working_dir: /workspace/frontend
    command: yarn run dev
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    env_file:
      - .env
    depends_on:
      - backend

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

volumes:
  postgres-data:
  backend-node-modules:
  frontend-node-modules: